FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY config.py .
COPY realtime_detector.py .

EXPOSE 8080

CMD ["python3", "realtime_detector.py"]
