FROM nginx:alpine

COPY target_monitor.sh /usr/local/bin/target_monitor.sh
RUN chmod +x /usr/local/bin/target_monitor.sh

CMD ["sh", "-c", "/usr/local/bin/target_monitor.sh & nginx -g 'daemon off;'"]
