events {
    worker_connections 1024;
}

http {
    upstream detector {
        server detector:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            return 200 'OK\n';
            add_header Content-Type text/plain;
        }

        location /health {
            return 200 'Nginx OK\n';
            add_header Content-Type text/plain;
        }
    }
}
