FROM nginx:alpine

RUN apk add --no-cache bash curl

COPY src/detection/target_monitor.sh /usr/local/bin/target_monitor.sh

RUN chmod +x /usr/local/bin/target_monitor.sh

CMD ["/bin/bash", "-c", "/usr/local/bin/target_monitor.sh & nginx -g 'daemon off;'"]
